language: ruby
cache: bundler
rvm:
- 2.2.3
script: "./_bin/deploy"
branches:
  only:
    - master
env:
  global:
    - GITHUB_REPO_SLUG=mysociety/kuvakazim
    - secure: fugkQ8M6ZfGHAg1NrmAoUaSlRMQ3jT5OFXKT+tP9BPCmP+Em4FIkrthUQu/xp3Dvo4SpJH43eR9gXMX+3Ci9l2IEJSzn4pZbf6+3OwD/lOF443SEatz8fhkB+0UOSYVOXnThVTbEQBwPIqYDXKenNZbPsfAsFOYlt1hvBBpsnzAF2F80MAY6lMIRO+0YdRH6FTos6FOuB72BneI69Ov8nqOpAh8lKVI9iJxZl/H0JQpGqztr+B6BrFXsWMHnvkCCgnced4X9h788nRjSdbjW8QPrEqaGQdbqCoX5vlUI76B1+TVy3uH6TP3qqRsz0ej3lUpeZTm64ihBhpiIT0czd/7RQ3BcDxtE9Pohd0JiYOVbSkXUaoTaWlaAej7EDGI8qLLPFRueUNV6F2HTNXUPL2GmOd+N2d4iYWyLVHWRiwfMmhjDHtkvtyB/J3Cbaz9H45vMNyLs2gHkwQfwnuvvdnICJ1ZHyRQm+oxY0VF5qOLR3IYHQKChLc5KzQCcGjhsBFkKmXzdu38dM1rc0lY4Iu0wdQNOwAoINQgJWAP6lWLtcudh0Sq6Q3XOe7s7fD687O8M9PG5Z7ZbgXoLpc+zSbJuWrFIUCuzF+6+c3RzEaO3jLBL98N2lGnFoES90waUQpQ47gqZliMynF2hzdDS0BlQrE3n7vTAEKqA+mBW/mU=
