# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kuvakazim
baseurl: ""
url: "http://www.kuvakazim.com"
twitter_username: KuvakaZim

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude: [Gemfile, Gemfile.lock]

defaults:
  -
    scope:
      path: "info"
    values:
      layout: page
