# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kuvakazim
baseurl: ""
url: "http://www.kuvakazim.com"
twitter_username: KuvakaZim
popolo_url: https://github.com/everypolitician/everypolitician-data/raw/master/data/Zimbabwe/Assembly/ep-popolo-v1.0.json

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude: [Gemfile, Gemfile.lock, vendor]

collections:
  persons:
    output: true
    permalink: '/person/:path/'
  organizations:
    output: true
    permalink: '/organisation/:path/'
  areas:
    output: true
    permalink: '/place/:path/'
  events:
    output: true
    permalink: '/event/:path/'

defaults:
  - scope:
      path: "info"
    values:
      layout: page
