# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KuvakaZim
email: chrism@mysociety.org
url: "http://staging.kuvakazim.com"
twitter_username: KuvakaZim

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude: [Gemfile, Gemfile.lock, vendor, README.md]

# TODO: Remove this and let _plugins/everypolitician_datasource.rb handle
# setting the source one the Zimbabwe data is on master.
everypolitician:
  sources:
    assembly: https://github.com/everypolitician/everypolitician-data/raw/kuvakazim/data/Zimbabwe/Assembly/ep-popolo-v1.0.json
    senate: https://github.com/everypolitician/everypolitician-data/raw/kuvakazim/data/Zimbabwe/Senate/ep-popolo-v1.0.json
  education: https://docs.google.com/spreadsheets/u/1/d/1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM/export?format=csv&id=1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM&gid=0

collections:

  # Assembly
  assembly_people:
    output: true
    permalink: '/assembly/person/:path/'
  assembly_organizations:
    output: true
    permalink: '/assembly/organisation/:path/'
  assembly_areas:
    output: true
    permalink: '/assembly/place/:path/'

  # Senate
  senate_people:
    output: true
    permalink: '/senate/person/:path/'
  senate_organizations:
    output: true
    permalink: '/senate/organisation/:path/'
  senate_areas:
    output: true
    permalink: '/senate/place/:path/'

defaults:
  - scope:
      path: "info"
    values:
      layout: page
      breadcrumbs:
        - Information
  - scope:
      path: "blog"
    values:
      breadcrumbs:
        - <a href="/blog">Blog</a>
