# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KuvakaZim
email: info@kuvakazim.com
url: "http://www.kuvakazim.com"
twitter_username: KuvakaZim
google_analytics:
  tracking_code: UA-45828301-1

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude: [Gemfile, Gemfile.lock, vendor, README.md, config.rb]

# Disable excerpt generation
excerpt_separator: ''

remote_csv:
  education:
    source: https://docs.google.com/spreadsheets/u/1/d/1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM/export?format=csv&id=1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM&gid=0
    collections:
      assembly_people: kuvakazim_id
      senate_people: kuvakazim_id
  executive_positions:
    source: https://docs.google.com/spreadsheets/u/1/d/1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM/export?format=csv&id=1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM&gid=1230746570
    group_by: role
    collection_slug_field: role
    reverse_relation_name: person
    collections:
      assembly_people: kuvakazim_id
      senate_people: kuvakazim_id
  job_history:
    source: https://docs.google.com/spreadsheets/u/1/d/1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM/export?format=csv&id=1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM&gid=724304320
    collections:
      assembly_people: kuvakazim_id
      senate_people: kuvakazim_id

collections_to_search:
  - assembly_people
  - senate_people
  - assembly_organizations
  - senate_organizations
  - assembly_areas
  - senate_areas

writeinpublic:
  subdomain: kuvakazim
  disabled: true

collections:
  executive_positions_by_role:
    output: true

  # Assembly
  assembly_people:
    output: true
    permalink: '/assembly/person/:path/'
  assembly_organizations:
    output: true
    permalink: '/assembly/organisation/:path/'
  assembly_areas:
    output: true
    permalink: '/assembly/place/:path/'

  # Senate
  senate_people:
    output: true
    permalink: '/senate/person/:path/'
  senate_organizations:
    output: true
    permalink: '/senate/organisation/:path/'
  senate_areas:
    output: true
    permalink: '/senate/place/:path/'

prose:
  siteurl: http://www.kuvakazim.com
  relativeLinks: http://www.kuvakazim.com/links.jsonp
  media: media_root
  ignore:
    - '*'
    - '!_posts'
    - '!info'
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: published
        field:
          element: checkbox
          label: Published
          value: true
    info:
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: permalink
        field:
          element: text
          label: Permalink
          value: ""

defaults:
  - scope:
      path: "info"
    values:
      layout: page
      breadcrumbs:
        - Information
  - scope:
      path: "blog"
    values:
      breadcrumbs:
        - <a href="/blog">Blog</a>
